import CONSTANTS from "./constants/constants";

export const MAGICITEMS = {};

MAGICITEMS.actors = CONSTANTS.MAGICITEMS.actors;

MAGICITEMS.rechargeUnits = CONSTANTS.MAGICITEMS.rechargeUnits;

MAGICITEMS.DAILY = CONSTANTS.MAGICITEMS.DAILY;
MAGICITEMS.DAWN = CONSTANTS.MAGICITEMS.DAWN;
MAGICITEMS.SUNSET = CONSTANTS.MAGICITEMS.SUNSET;
MAGICITEMS.SHORT_REST = CONSTANTS.MAGICITEMS.SHORT_REST;
MAGICITEMS.LONG_REST = CONSTANTS.MAGICITEMS.LONG_REST;

MAGICITEMS.rechargeTypes = CONSTANTS.MAGICITEMS.rechargeTypes;

MAGICITEMS.destroyChecks = CONSTANTS.MAGICITEMS.destroyChecks;

MAGICITEMS.destroyTypes = CONSTANTS.MAGICITEMS.destroyTypes;

MAGICITEMS.chargeTypes = CONSTANTS.MAGICITEMS.chargeTypes;

MAGICITEMS.effects = CONSTANTS.MAGICITEMS.effects;

MAGICITEMS.CHARGE_TYPE_WHOLE_ITEM = CONSTANTS.MAGICITEMS.CHARGE_TYPE_WHOLE_ITEM;
MAGICITEMS.CHARGE_TYPE_PER_SPELL = CONSTANTS.MAGICITEMS.CHARGE_TYPE_PER_SPELL;

MAGICITEMS.NUMERIC_RECHARGE = CONSTANTS.MAGICITEMS.NUMERIC_RECHARGE;
MAGICITEMS.FORMULA_RECHARGE = CONSTANTS.MAGICITEMS.FORMULA_RECHARGE;
MAGICITEMS.FORMULA_FULL = CONSTANTS.MAGICITEMS.FORMULA_FULL;

MAGICITEMS.tableUsages = CONSTANTS.MAGICITEMS.tableUsages;

MAGICITEMS.TABLE_USAGE_AS_SPELL = CONSTANTS.MAGICITEMS.TABLE_USAGE_AS_SPELL;
MAGICITEMS.TABLE_USAGE_AS_FEAT = CONSTANTS.MAGICITEMS.TABLE_USAGE_AS_FEAT;
MAGICITEMS.TABLE_USAGE_TRIGGER = CONSTANTS.MAGICITEMS.TABLE_USAGE_TRIGGER;

MAGICITEMS.localized = CONSTANTS.MAGICITEMS.localized;

MAGICITEMS.numeric = CONSTANTS.MAGICITEMS.numeric;
